export const SCREEN_WIDTH = 320;
export const SCREEN_HEIGHT = 200;
export const TILE_SIZE = 16;
export const PLAYER_INITIAL_X_OFFS = 8;
export const PLAYER_INITIAL_Y_OFFS = 11;
export const PLAYER_INITIAL_SPEED = 2; // tiles per second
export const ENEMY_INITIAL_X_OFFS = 8;
export const ENEMY_INITIAL_Y_OFFS = 8;
export const ENEMY_SPEED = [1, 2]; // tiles per second for each enemy type
export const BOMB_FUSE_TIME = 4; // seconds
